import { Link } from "react-router-dom";
import { Database, FileText, LockKeyhole, ShieldCheck, Trash2 } from "lucide-react";

import { useWorkspace } from "@/context/WorkspaceContext";

export default function PrivacyPage() {
  const { workspace, acceptPrivacy, clearWorkspace } = useWorkspace();
  const handleDelete = () => {
    if (window.confirm("¿Eliminar todos los datos guardados por nexTalent en este navegador?")) clearWorkspace();
  };
  return <div data-testid="privacy-page" className="min-h-screen" style={{ backgroundColor: "var(--parchment)" }}><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs mb-4" style={{ backgroundColor: "rgba(201,100,66,0.08)", color: "var(--terracotta)", fontWeight: 600 }}><ShieldCheck size={14} /> Privacidad por diseño</div><h1 className="font-serif text-4xl mb-3" style={{ color: "var(--near-black)" }}>Tus datos profesionales, bajo tu control</h1><p className="text-base mb-8" style={{ color: "var(--olive-gray)" }}>Esta versión combina procesamiento temporal en la API con un espacio personal guardado localmente en tu navegador.</p><div className="grid md:grid-cols-2 gap-4 mb-8">{[
    { icon: FileText, title: "CV temporal", text: "El archivo se guarda en un fichero temporal durante el análisis y se elimina al terminar la petición." },
    { icon: Database, title: "Espacio personal local", text: "Perfil, guardados, planes, progreso y candidaturas se conservan en localStorage; todavía no existe una cuenta remota." },
    { icon: LockKeyhole, title: "Procesamiento con IA", text: "El texto extraído se envía al proveedor LLM configurado (actualmente Groq) para estructurar el perfil; los embeddings se generan con Ollama. Consulta también las condiciones del proveedor desplegado." },
    { icon: Trash2, title: "Derecho a borrar", text: "Puedes eliminar todo el espacio personal desde esta página o desde Mi espacio." },
  ].map(({ icon: Icon, title, text }) => <section key={title} className="rounded-2xl p-5" style={{ backgroundColor: "var(--ivory)", border: "1px solid var(--border-cream)" }}><Icon size={20} style={{ color: "var(--terracotta)" }} /><h2 className="font-serif text-xl mt-3 mb-2" style={{ color: "var(--near-black)" }}>{title}</h2><p className="text-sm" style={{ color: "var(--olive-gray)" }}>{text}</p></section>)}</div><section className="rounded-2xl p-6 mb-6" style={{ backgroundColor: "var(--ivory)", border: "1px solid var(--border-cream)" }}><h2 className="font-serif text-2xl mb-3" style={{ color: "var(--near-black)" }}>Consentimiento informado</h2><p className="text-sm mb-4" style={{ color: "var(--olive-gray)" }}>Al analizar un CV confirmas que tienes derecho a utilizarlo y aceptas su procesamiento para generar recomendaciones. No utilices documentación de otra persona.</p>{workspace.privacyAcceptedAt ? <p className="inline-flex items-center gap-2 text-sm" style={{ color: "#5c7052", fontWeight: 600 }}><ShieldCheck size={16} /> Consentimiento registrado en este navegador.</p> : <button onClick={acceptPrivacy} className="px-4 py-2 rounded-lg text-sm" style={{ backgroundColor: "var(--terracotta)", color: "var(--ivory)", fontWeight: 600 }}>Aceptar y continuar</button>}</section><div className="flex flex-col sm:flex-row gap-3"><Link to="/workspace" className="px-4 py-2 rounded-lg text-sm text-center" style={{ backgroundColor: "var(--warm-sand)", color: "var(--near-black)", fontWeight: 600 }}>Volver a Mi espacio</Link><button onClick={handleDelete} className="px-4 py-2 rounded-lg text-sm" style={{ color: "var(--error-crimson)", border: "1px solid rgba(181,51,51,0.25)" }}>Eliminar todos mis datos locales</button></div></div></div>;
}
